### ISSUE TITLE
Dictionary definitions are failing to load

### ISSUE THREAD

**Issue by johnblommers** [wardellbagby/lyricistant#46]
**Describe the bug**
The word lookup feature always displays "No Definition Found."

**To Reproduce**

1. Open any lyric
2. Select a word
3. Click the AZ icon
4. See e rrorNo Definition Found

**Expected behavior**
The meaning of the word and possible synomyms and antonyms listed

**Screenshots**

![Screenshot from 2022-12-03 18-42-27](https://user-images.githubusercontent.com/8484427/205471508-0611f647-670b-4b58-ac51-0519e5110c12.png)

**Desktop (please complete the following information when using the desktop apps):**

- OS: PopOS 22.04
- Lyricistant version Lyricistant - 2.1.0-nightly+a8a5ea8

**Browser (please complete the following information when using the website):**

- Browser: N/A
- URL:N/A

**Logs: (Preferences -> About Lyricistant -> Download Logs)**
[logs.txt](https://github.com/wardellbagby/lyricistant/files/10147754/logs.txt)

**Additional Context:**

Perhaps the protocol with the dictionary server isn't working as the logs show this:

````
[875281:1203/183436.287223:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[875281:1203/183436.292860:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for api.dictionaryapi.dev failed:
----- Certificate i=0 (CN=api.dictionaryapi.dev) -----
ERROR: Time is after notAfter
```

**Comment by wardellbagby** [comment]
Yup, looks like the certificate for api.dictionaryapi.dev has expired.

It'll _probably_ resolve itself eventually but I've been meaning to look for some alternatives anyway so I'll use this as an opportunity to do that.

**Comment by wardellbagby** [comment]
Issue for the original repo: https://github.com/meetDeveloper/freeDictionaryAPI/issues/167

**Comment by wardellbagby** [comment]
Just needed a bit of time; this is working again. Still the best Dictionary API out there so we're still gonna stick with it.
